plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
command = "python3 scripts/generate-rss.py"
publish = "C:\\Users\\Ray\\Desktop\\wangrenmin-blog"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]